/**
 * Updated PageSettingsForm với integration mới
 * Refactored theo Clean Architecture
 */

'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { AlertCircle, CheckCircle, Lock } from 'lucide-react';
import { Page, PageStatus, DynamicConfig } from '@/types/page-builder';
import { DynamicPageConfig } from './DynamicPageConfig';
import { PageLayoutSettings } from '@/features/page-builder/components/PageLayoutSettings';
import { usePageLayout } from '@/features/page-builder/hooks/usePageLayout';

/**
 * Vietnamese character transliteration map
 */
const VIETNAMESE_CHAR_MAP: Record<string, string> = {
  'à': 'a', 'á': 'a', 'ả': 'a', 'ã': 'a', 'ạ': 'a',
  'ă': 'a', 'ằ': 'a', 'ắ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
  'â': 'a', 'ầ': 'a', 'ấ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a',
  'đ': 'd',
  'è': 'e', 'é': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ẹ': 'e',
  'ê': 'e', 'ề': 'e', 'ế': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
  'ì': 'i', 'í': 'i', 'ỉ': 'i', 'ĩ': 'i', 'ị': 'i',
  'ò': 'o', 'ó': 'o', 'ỏ': 'o', 'õ': 'o', 'ọ': 'o',
  'ô': 'o', 'ồ': 'o', 'ố': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o',
  'ơ': 'o', 'ờ': 'o', 'ớ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
  'ù': 'u', 'ú': 'u', 'ủ': 'u', 'ũ': 'u', 'ụ': 'u',
  'ư': 'u', 'ừ': 'u', 'ứ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
  'ỳ': 'y', 'ý': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y',
  'À': 'a', 'Á': 'a', 'Ả': 'a', 'Ã': 'a', 'Ạ': 'a',
  'Ă': 'a', 'Ằ': 'a', 'Ắ': 'a', 'Ẳ': 'a', 'Ẵ': 'a', 'Ặ': 'a',
  'Â': 'a', 'Ầ': 'a', 'Ấ': 'a', 'Ẩ': 'a', 'Ẫ': 'a', 'Ậ': 'a',
  'Đ': 'd',
  'È': 'e', 'É': 'e', 'Ẻ': 'e', 'Ẽ': 'e', 'Ẹ': 'e',
  'Ê': 'e', 'Ề': 'e', 'Ế': 'e', 'Ể': 'e', 'Ễ': 'e', 'Ệ': 'e',
  'Ì': 'i', 'Í': 'i', 'Ỉ': 'i', 'Ĩ': 'i', 'Ị': 'i',
  'Ò': 'o', 'Ó': 'o', 'Ỏ': 'o', 'Õ': 'o', 'Ọ': 'o',
  'Ô': 'o', 'Ồ': 'o', 'Ố': 'o', 'Ổ': 'o', 'Ỗ': 'o', 'Ộ': 'o',
  'Ơ': 'o', 'Ờ': 'o', 'Ớ': 'o', 'Ở': 'o', 'Ỡ': 'o', 'Ợ': 'o',
  'Ù': 'u', 'Ú': 'u', 'Ủ': 'u', 'Ũ': 'u', 'Ụ': 'u',
  'Ư': 'u', 'Ừ': 'u', 'Ứ': 'u', 'Ử': 'u', 'Ữ': 'u', 'Ự': 'u',
  'Ỳ': 'y', 'Ý': 'y', 'Ỷ': 'y', 'Ỹ': 'y', 'Ỵ': 'y',
};

function transliterateToSlug(text: string): string {
  if (!text) return '';
  
  let slug = text
    .split('')
    .map(char => VIETNAMESE_CHAR_MAP[char] || char)
    .join('');
  
  slug = slug.toLowerCase();
  slug = slug
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
  slug = slug.replace(/^-+|-+$/g, '');
  
  return slug;
}

interface PageSettingsFormProps {
  page: Page;
  onUpdate: (page: Page) => void;
}

const getStatusDescription = (status: PageStatus) => {
  switch (status) {
    case PageStatus.DRAFT:
      return {
        title: 'Draft (Bản Nháp)',
        description: 'Trang này đang được soạn thảo. Không hiển thị công khai cho khách truy cập.',
        icon: <AlertCircle className="w-5 h-5" />,
        color: 'text-yellow-600',
      };
    case PageStatus.PUBLISHED:
      return {
        title: 'Published (Xuất Bản)',
        description: 'Trang này đang hiển thị công khai. Tất cả khách truy cập có thể xem.',
        icon: <CheckCircle className="w-5 h-5" />,
        color: 'text-green-600',
      };
    case PageStatus.ARCHIVED:
      return {
        title: 'Archived (Lưu Trữ)',
        description: 'Trang này được lưu trữ. Không hiển thị công khai nhưng vẫn có thể khôi phục.',
        icon: <Lock className="w-5 h-5" />,
        color: 'text-gray-600',
      };
  }
};

export default function PageSettingsForm({ page, onUpdate }: PageSettingsFormProps) {
  const [formData, setFormData] = useState({
    title: page.title || '',
    slug: page.slug || '',
    content: (page.content && typeof page.content === 'string') ? page.content : '',
    status: page.status,
    isHomepage: page.isHomepage ?? false,
    isDynamic: page.isDynamic ?? false,
    dynamicConfig: page.dynamicConfig,
    seoTitle: page.seoTitle || '',
    seoDescription: page.seoDescription || '',
    seoKeywords: (page.seoKeywords || []).join(', '),
  });

  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(
    page.slug === '' || page.slug?.startsWith('untitled')
  );
  const [showStatusChangeDialog, setShowStatusChangeDialog] = useState(false);
  const [pendingStatus, setPendingStatus] = useState<PageStatus | null>(null);

  // 🆕 Use layout hook
  const { settings: layoutSettings, updateSetting: updateLayoutSetting } = usePageLayout({
    initialSettings: page.layoutSettings,
    onChange: (newSettings) => {
      const updatedPage = {
        ...page,
        ...formData,
        layoutSettings: newSettings,
        seoKeywords: formData.seoKeywords.split(',').map(k => k.trim()).filter(Boolean),
      };
      onUpdate(updatedPage);
    },
  });

  const currentStatusInfo = getStatusDescription(formData.status);

  const handleInputChange = (field: keyof typeof formData, value: any) => {
    if (field === 'status' && value !== formData.status) {
      setPendingStatus(value as PageStatus);
      setShowStatusChangeDialog(true);
      return;
    }

    const newFormData = { ...formData, [field]: value };
    
    if (field === 'title' && isSlugAutoGenerated) {
      const generatedSlug = transliterateToSlug(value);
      newFormData.slug = generatedSlug;
    }
    
    if (field === 'slug') {
      setIsSlugAutoGenerated(false);
    }
    
    setFormData(newFormData);
    
    const updatedPage = {
      ...page,
      ...newFormData,
      layoutSettings,
      content: field === 'content' && !value ? undefined : (field === 'content' ? value : page.content),
      seoKeywords: field === 'seoKeywords' 
        ? value.split(',').map((k: string) => k.trim()).filter(Boolean) 
        : page.seoKeywords,
    };
    onUpdate(updatedPage);
  };

  const handleConfirmStatusChange = () => {
    if (pendingStatus) {
      setFormData({ ...formData, status: pendingStatus });
      const updatedPage = {
        ...page,
        ...formData,
        status: pendingStatus,
        layoutSettings,
        seoKeywords: formData.seoKeywords.split(',').map((k: string) => k.trim()).filter(Boolean),
      };
      onUpdate(updatedPage);
    }
    setShowStatusChangeDialog(false);
    setPendingStatus(null);
  };

  const pendingStatusInfo = pendingStatus ? getStatusDescription(pendingStatus) : null;

  return (
    <>
      <Tabs defaultValue="general" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="general">Tổng Quát</TabsTrigger>
          <TabsTrigger value="layout">Bố Cục</TabsTrigger>
          <TabsTrigger value="seo">SEO</TabsTrigger>
        </TabsList>

        {/* General Tab */}
        <TabsContent value="general" className="space-y-4 mt-4">
          <div className="space-y-2">
            <Label htmlFor="title">Tiêu Đề Trang</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => handleInputChange('title', e.target.value)}
              placeholder="Nhập tiêu đề trang..."
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">Slug (URL)</Label>
            <Input
              id="slug"
              value={formData.slug}
              onChange={(e) => handleInputChange('slug', e.target.value)}
              placeholder="vi-du-slug-url"
            />
            <p className="text-xs text-muted-foreground">
              {isSlugAutoGenerated ? '🤖 Tự động tạo từ tiêu đề' : '✏️ Được chỉnh sửa thủ công'}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="content">Mô Tả Ngắn</Label>
            <Textarea
              id="content"
              value={formData.content}
              onChange={(e) => handleInputChange('content', e.target.value)}
              placeholder="Mô tả ngắn về trang (tùy chọn)..."
              rows={3}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="status">Trạng Thái</Label>
            <Select value={formData.status} onValueChange={(value) => handleInputChange('status', value)}>
              <SelectTrigger id="status">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={PageStatus.DRAFT}>Bản Nháp</SelectItem>
                <SelectItem value={PageStatus.PUBLISHED}>Xuất Bản</SelectItem>
                <SelectItem value={PageStatus.ARCHIVED}>Lưu Trữ</SelectItem>
              </SelectContent>
            </Select>
            <div className={`flex items-center gap-2 text-sm ${currentStatusInfo.color}`}>
              {currentStatusInfo.icon}
              <span>{currentStatusInfo.description}</span>
            </div>
          </div>

          <div className="border-t pt-4">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label htmlFor="isHomepage">Trang Chủ</Label>
                <p className="text-xs text-muted-foreground">
                  Đặt trang này làm trang chủ của website
                </p>
              </div>
              <Switch
                id="isHomepage"
                checked={formData.isHomepage || false}
                onCheckedChange={(checked) => handleInputChange('isHomepage', checked)}
              />
            </div>
          </div>

          <div className="border-t pt-4">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label htmlFor="isDynamic">Dynamic Page Template</Label>
                <p className="text-xs text-muted-foreground">
                  Sử dụng trang này làm template cho nhiều items với slug khác nhau
                </p>
              </div>
              <Switch
                id="isDynamic"
                checked={formData.isDynamic || false}
                onCheckedChange={(checked) => handleInputChange('isDynamic', checked)}
              />
            </div>
            {formData.isDynamic && (
              <div className="mt-4">
                <DynamicPageConfig
                  config={formData.dynamicConfig}
                  blocks={page.blocks}
                  onChange={(config) => handleInputChange('dynamicConfig', config)}
                />
              </div>
            )}
          </div>
        </TabsContent>

        {/* Layout Tab - 🆕 Refactored */}
        <TabsContent value="layout" className="mt-4">
          <PageLayoutSettings
            settings={layoutSettings}
            onChange={(newSettings) => {
              const updatedPage = {
                ...page,
                ...formData,
                layoutSettings: newSettings,
                seoKeywords: formData.seoKeywords.split(',').map(k => k.trim()).filter(Boolean),
              };
              onUpdate(updatedPage);
            }}
          />
        </TabsContent>

        {/* SEO Tab */}
        <TabsContent value="seo" className="space-y-4 mt-4">
          <div className="space-y-2">
            <Label htmlFor="seoTitle">Tiêu Đề SEO</Label>
            <Input
              id="seoTitle"
              value={formData.seoTitle}
              onChange={(e) => handleInputChange('seoTitle', e.target.value)}
              placeholder="Tiêu đề tối ưu cho SEO (50-60 ký tự)..."
            />
            <p className="text-xs text-muted-foreground">
              {formData.seoTitle.length}/60 ký tự
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="seoDescription">Mô Tả SEO</Label>
            <Textarea
              id="seoDescription"
              value={formData.seoDescription}
              onChange={(e) => handleInputChange('seoDescription', e.target.value)}
              placeholder="Mô tả ngắn gọn về nội dung trang (150-160 ký tự)..."
              rows={3}
            />
            <p className="text-xs text-muted-foreground">
              {formData.seoDescription.length}/160 ký tự
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="seoKeywords">Từ Khóa SEO</Label>
            <Input
              id="seoKeywords"
              value={formData.seoKeywords}
              onChange={(e) => handleInputChange('seoKeywords', e.target.value)}
              placeholder="từ khóa 1, từ khóa 2, từ khóa 3..."
            />
            <p className="text-xs text-muted-foreground">
              Phân cách các từ khóa bằng dấu phẩy
            </p>
          </div>
        </TabsContent>
      </Tabs>

      {/* Status Change Confirmation Dialog */}
      <Dialog open={showStatusChangeDialog} onOpenChange={setShowStatusChangeDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Xác Nhận Thay Đổi Trạng Thái</DialogTitle>
            <DialogDescription>
              Bạn có chắc chắn muốn thay đổi trạng thái trang?
            </DialogDescription>
          </DialogHeader>
          
          {pendingStatusInfo && (
            <div className="py-4 space-y-4">
              <div className="flex items-start gap-3">
                <div className={pendingStatusInfo.color}>
                  {pendingStatusInfo.icon}
                </div>
                <div className="space-y-1">
                  <h4 className="font-semibold">{pendingStatusInfo.title}</h4>
                  <p className="text-sm text-muted-foreground">
                    {pendingStatusInfo.description}
                  </p>
                </div>
              </div>
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowStatusChangeDialog(false)}>
              Hủy
            </Button>
            <Button onClick={handleConfirmStatusChange}>
              Xác Nhận
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
